### ISSUE TITLE
Boolean value of this clause is not defined

### ISSUE THREAD

**Issue by nexter83** [PlaidCloud/sqlalchemy-greenplum#12]
Hello.
I have an error. 
Statement:
```
Traceback (most recent call last):
  File "/home/nexter/SqlAlchemyTest/test.py", line 23, in <module>
    t.metadata.create_all(engine)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4741, in create_all
    bind._run_ddl_visitor(
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2979, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2016, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 846, in visit_metadata
    self.traverse_single(
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 483, in traverse_single
    return meth(obj, **kw)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 890, in visit_table
    self.connection.execute(
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_ddl
    compiled = ddl.compile(
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 504, in compile
    return self._compiler(dialect, **kw)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 4001, in visit_create_table
    text += "\n)%s\n\n" % self.post_create_table(table)
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy_greenplum/dialect.py", line 84, in post_create_table
    if gp_opts['distributed_by']:
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 590, in __bool__
    raise TypeError("Boolean value of this clause is not defined")
TypeError: Boolean value of this clause is not defined
```
gp_opts['distributed_by'] is an alchemy class <class 'sqlalchemy.sql.schema.Column'> 

if i use follow code thats work
File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy_greenplum/dialect.py", line 84, in 
```
        if str(gp_opts['distributed_by']):
            if str(gp_opts['distributed_by']).upper() == 'RANDOM':
```

**Comment by rad-pat** [comment]
Thanks for the issue, can you please let us know what SQLAlchemy version and what you are running to get the error?

**Comment by nexter83** [comment]
version SQLAlchemy 1.4.50 i run this test code

```
from sqlalchemy import Column, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine

Base = declarative_base()


class TestODS(Base):
    __tablename__ = "test_table"

    md5_key = Column(String, primary_key=True)
    activnost = Column(String)

    __table_args__ = {"greenplum_distributed_by": md5_key}


t = TestODS()
engine = create_engine(
    "greenplum://***:***@localhost:5432/postgres", echo=True
)

t.metadata.create_all(engine)
```

**Comment by nexter83** [comment]
i tried this code and i have no error
```
        if str(gp_opts['distributed_by']):
            if str(gp_opts['distributed_by']).upper() == 'RANDOM':
                table_opts.append('\n DISTRIBUTED RANDOMLY')
            else:
                table_opts.append('\n DISTRIBUTED BY ({0})'.format(gp_opts['distributed_by'].key))
```
i used format(gp_opts['distributed_by'].**key**) because without **key** there was an error from psycopg2

```
  File "/home/nexter/SqlAlchemyTest/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "DISTRIBUTED"
LINE 7:  DISTRIBUTED BY (test_table.md5_key)
```

**Comment by rad-pat** [comment]
Can you please try the following, md5_key is a Column object. The distributed_by just requires the column name(s) as a string so either 'column1', or 'column1, column2, column3'
```
from sqlalchemy import Column, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine

Base = declarative_base()


class TestODS(Base):
    __tablename__ = "test_table"

    md5_key = Column(String, primary_key=True)
    activnost = Column(String)

    __table_args__ = {"greenplum_distributed_by": "md5_key"}


t = TestODS()
engine = create_engine(
    "greenplum://***:***@localhost:5432/postgres", echo=True
)

t.metadata.create_all(engine)
```

**Comment by nexter83** [comment]
yes, it's helped me. thank you
